In [3]:
import  numpy as np

arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr)
print(arr.dtype)
print(np.__version__)

<class 'numpy.ndarray'>
[1 2 3 4 5]
int64
2.3.5


In [4]:
tup  = (1,2,3,4,5,6)
array = np.array(tup)
print(array)

data = [[1,2,3,4,5],[6,7,8,9,0]]

array = np.array(data)
print(array)
print(array.ndim)

[1 2 3 4 5 6]
[[1 2 3 4 5]
 [6 7 8 9 0]]
2


In [5]:
ar = np.zeros((2,4))
print(ar)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [28]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [31]:
arr = np.random.rand(2,3)
print(arr)

[[0.90467981 0.68844197 0.0095958 ]
 [0.11280664 0.3183569  0.77208155]]


**#indexing and slicing (Critical for ML)**

In [39]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(a[0])
print(a[2:5])
print(a[1:4])

[1 2 3 4 5 6 7 8]
1
[3 4 5]
[2 3 4]


**#2D slicing**

In [7]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b[0,1])
print(b[0,3])
print(b[:,1])
print(b[1,:])

2
4
[2 6]
[5 6 7 8]


**#Mathemetical Operation**

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


**#Broadcasting (SUPER IMPORTANT)**

In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print(a+b)

[[2 4 6]
 [5 7 9]]


**#matrix multiplication***

In [17]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a,b))

print(np.linalg.det(a))

[[19 22]
 [43 50]]
-2.0000000000000004


In [19]:
print(np.linalg.inv(a))
print(np.linalg.eig(a))

[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [31]:
a = np.array([1,2,3,4,5])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a))


3.0
3.0
1.4142135623730951
2.0
1
5
15


**#For axis***

In [33]:
b = np.array([[1,2,3,4],[6,7,8,9]])
np.mean(b,axis=0)
np.mean(b,axis=1)

array([2.5, 7.5])

**#Random Module (Used in ML)**

In [45]:
np.random.rand(3)
print(np.random.randn(4))
print(np.random.randint(1,20,3))

[-0.27810347 -0.93331372 -2.09186394 -0.48475701]
[2 5 3]
